package com.seckkill.domain;

public class Order {

    private String id;
    private Integer userId;
    private Integer itemId;
    private Integer promoId;
    private Double itemPrice;
    private Integer amount;
    private Double orderPrice;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.item_id
     *
     * @return the value of order.item_id
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.item_id
     *
     * @param itemId the value for order.item_id
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.item_price
     *
     * @return the value of order.item_price
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.item_price
     *
     * @param itemPrice the value for order.item_price
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_price
     *
     * @return the value of order.order_price
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public Double getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_price
     *
     * @param orderPrice the value for order.order_price
     *
     * @mbg.generated Tue Dec 25 10:34:27 CST 2018
     */
    public void setOrderPrice(Double orderPrice) {
        this.orderPrice = orderPrice;
    }

    public Integer getPromoId() {
        return promoId;
    }

    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }
}